# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: node.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'node.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnode.proto\x12\tisek_node\"@\n\x0b\x43\x61llRequest\x12\x0e\n\x06sender\x18\x01 \x01(\t\x12\x10\n\x08receiver\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x1d\n\x0c\x43\x61llResponse\x12\r\n\x05reply\x18\x01 \x01(\t2J\n\x0fIsekNodeService\x12\x37\n\x04\x63\x61ll\x12\x16.isek_node.CallRequest\x1a\x17.isek_node.CallResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'node_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CALLREQUEST']._serialized_start=25
  _globals['_CALLREQUEST']._serialized_end=89
  _globals['_CALLRESPONSE']._serialized_start=91
  _globals['_CALLRESPONSE']._serialized_end=120
  _globals['_ISEKNODESERVICE']._serialized_start=122
  _globals['_ISEKNODESERVICE']._serialized_end=196
# @@protoc_insertion_point(module_scope)
